=== sparkgeo/physrisk-cli/json_schema/request/current/current_request_schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "physrisk_request",
    "description": "Physrisk request object",
    "type": "object",
    "properties": {
        "assets": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "asset_class": {
                                "type": "string"
                            },
                            "type": {
                                "type": "string"
                            },
                            "location": {
                                "type": "string"
                            },
                            "latitude": {
                                "type": "number",
                                "minimum": -90,
                                "maximum": 90
                            },
                            "longitude": {
                                "type": "number",
                                "minimum": -180,
                                "maximum": 180
                            }
                        },
                        "required": [
                            "asset_class",
                            "latitude",
                            "longitude"
                        ]
                    }
                }
            },
            "required": [
                "items"
            ]
        },
        "include_asset_level": {
            "type": "boolean"
        },
        "include_calc_details": {
            "type": "boolean"
        },
        "include_measures": {
            "type": "boolean"
        },
        "years": {
            "type": "array",
            "items": {
                "type": "integer"
            }
        },
        "scenarios": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": [
                    "ssp126",
                    "ssp245",
                    "ssp585"
                ]
            }
        }
    },
    "required": [
        "assets",
        "include_asset_level",
        "include_calc_details",
        "include_measures",
        "years",
        "scenarios"
    ]
}

=== sparkgeo/physrisk-cli/json_schema/current_request_example.json
{
    "assets": {
        "items": [
            {
                "asset_class": "IndustrialActivity",
                "type": "Construction",
                "location": "Asia",
                "latitude": 32.322,
                "longitude": 65.119
            },
            {
                "asset_class": "IndustrialActivity",
                "type": "Construction",
                "location": "South America",
                "latitude": -39.1009,
                "longitude": -68.5982
            }
        ]
    },
    "include_asset_level": true,
    "include_calc_details": true,
    "include_measures": true,
    "years": [
        2030,
        2040
    ],
    "scenarios": [
        "ssp126",
        "ssp245"    ]
}
